[project]
name = "databpy"
version = "0.0.9"
description = "A data-oriented wrapper library for the Blender Python API"
readme = "README.md"
dependencies = ["numpy"]
requires-python = "~=3.11.0"
keywords = ["blender", "python", "numpy"]
maintainers = [{ name = "Brady Johnston", email = "brady.johnston@me.com" }]

[project.urls]
Homepage = "https://bradyajohnston.github.io/databpy"
Repository = "https://github.com/bradyajohnston/databpy"
Dcumentation = "https://bradyajohnston.github.io/databpy"

[project.optional-dependencies]
bpy = ["bpy>=4.2"]
test = ["pytest", "pytest-cov", "syrupy"]
dev = ["fake-bpy-module", "polars"]
docs = ["quartodoc", "jupyter", "polars"]
